FROM ubuntu:18.04

EXPOSE 9080

ARG numGrupo
ENV GROUP_NUMBER ${numGrupo: 36}

RUN apt-get update \
    && apt-get install -y git
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git
RUN apt-get update
RUN apt-get install -y python3-pip

WORKDIR practica_creativa2/bookinfo/src/productpage

RUN pip3 install -r requirements.txt

RUN sed -i '/Simple Bookstore App/c {% block title %}({{ GROUP_NUMBER }}) Simple Bookstore App{% endblock %}' templates/productpage.html

CMD python3 productpage_monolith.py 9080
