FROM ubuntu:18.04

EXPOSE 9080

ENV GROUP_NUMBER=0

RUN apt-get update \
    && apt-get install -y git
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git
RUN apt-get update
RUN apt-get install -y python3-pip

WORKDIR practica_creativa2/bookinfo/src/productpage

RUN pip3 install -r requirements.txt

WORKDIR /practica_creativa2/bookinfo/src/productpage/templates/

CMD sed -i "s/Simple\sBookstore\sApp/Simple Bookstore App - GRUPO ${GROUP_NUMBER}/g" index.html; \
    sed -i "s/Simple\sBookstore\sApp/Simple Bookstore App - GRUPO ${GROUP_NUMBER}/g" productpage.html; \
    python3 /practica_creativa2/bookinfo/src/productpage/productpage_monolith.py 9080
